# Generated by Django 3.2.3 on 2021-06-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infomation',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('photo_song_url', models.CharField(max_length=100)),
                ('photo_face_url', models.CharField(max_length=100)),
                ('photo_songer_url', models.CharField(max_length=100)),
                ('words', models.TextField()),
                ('song_time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('good', models.IntegerField()),
            ],
        ),
    ]
