# Generated by Django 3.2.3 on 2021-06-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lo_name', models.CharField(max_length=30, unique=True)),
                ('lo_pwd', models.CharField(max_length=30)),
            ],
        ),
    ]
