# Generated by Django 3.2.3 on 2021-06-29 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SongInfomation', '0001_initial'),
        ('OAUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('once_good', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SongInfomation.infomation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='OAUser.oauser')),
            ],
        ),
    ]
