# Generated by Django 3.2.3 on 2021-06-28 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SongInfomation', '0001_initial'),
        ('OAUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SongInfomation.infomation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='OAUser.oauser')),
            ],
        ),
    ]
